# Generated by Django 6.0.3 on 2026-03-24 06:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_pair', models.CharField(max_length=20)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('spread_percent', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('effective_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('is_simulated', models.BooleanField(default=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(default='SIMULATED - Connect Binance API for live rates', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payer_number', models.CharField(blank=True, help_text='EcoCash number or bank account', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account', models.CharField(blank=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('awaiting', 'Awaiting Payment'), ('received', 'Payment Received'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='awaiting', max_length=20)),
                ('payment_proof', models.TextField(blank=True, help_text='Proof of payment description')),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemFloat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('minimum_threshold', models.DecimalField(decimal_places=2, default=200, max_digits=12)),
                ('is_simulated', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(default='SIMULATED - Connect real accounts for live balances', max_length=200)),
            ],
        ),
    ]
