# Generated by Django 6.0.3 on 2026-03-27 00:00

import decimal
from django.db import migrations, models


def create_fee_settings(apps, schema_editor):
    FeeSettings = apps.get_model('payments', 'FeeSettings')
    FeeSettings.objects.get_or_create(
        pk=1,
        defaults={
            'deposit_fee_percent': decimal.Decimal('3.00'),
            'withdrawal_fee_percent': decimal.Decimal('3.00'),
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_fee_percent', models.DecimalField(decimal_places=2, default=decimal.Decimal('3.00'), max_digits=5)),
                ('withdrawal_fee_percent', models.DecimalField(decimal_places=2, default=decimal.Decimal('3.00'), max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fee Settings',
                'verbose_name_plural': 'Fee Settings',
            },
        ),
        migrations.RunPython(create_fee_settings, migrations.RunPython.noop),
    ]
