# Generated by Django 4.2.23 on 2026-03-28 09:35

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def dedupe_system_float_names(apps, schema_editor):
    SystemFloat = apps.get_model('payments', 'SystemFloat')
    db_alias = schema_editor.connection.alias

    for name in SystemFloat.objects.using(db_alias).values_list('name', flat=True).distinct():
        duplicates = list(SystemFloat.objects.using(db_alias).filter(name=name).order_by('id'))
        if len(duplicates) <= 1:
            continue

        primary = duplicates[0]
        for duplicate in duplicates[1:]:
            primary.balance += duplicate.balance
            primary.minimum_threshold = max(primary.minimum_threshold, duplicate.minimum_threshold)
            if not primary.note and duplicate.note:
                primary.note = duplicate.note
            duplicate.delete()
        primary.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0003_transaction_fee_percent_applied'),
        ('payments', '0003_feesettings'),
    ]

    operations = [
        migrations.RunPython(dedupe_system_float_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='feesettings',
            name='deposit_fee_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='feesettings',
            name='withdrawal_fee_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='systemfloat',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='FloatLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=255)),
                ('actor_label', models.CharField(default='system', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('system_float', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='payments.systemfloat')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='float_ledger_entries', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Float Ledger Entry',
                'verbose_name_plural': 'Float Ledger Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeSettingsAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_deposit_fee_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('new_deposit_fee_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('previous_withdrawal_fee_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('new_withdrawal_fee_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('changed_by_label', models.CharField(default='system', max_length=150)),
                ('source', models.CharField(choices=[('admin_panel', 'Admin Panel'), ('django_admin', 'Django Admin'), ('system', 'System')], default='system', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_setting_changes', to=settings.AUTH_USER_MODEL)),
                ('fee_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='payments.feesettings')),
            ],
            options={
                'verbose_name': 'Fee Settings Audit Log',
                'verbose_name_plural': 'Fee Settings Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
