# Generated by Django 4.2.23 on 2026-04-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_feesettings_deposit_fee_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_status',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='payment',
            name='received_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
