# Generated by Django 6.0.3 on 2026-03-24 06:35

import transactions.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=20)),
                ('platform', models.CharField(choices=[('binance', 'Binance'), ('weltrade', 'Weltrade'), ('exness', 'Exness'), ('xm', 'XM'), ('other', 'Other Broker')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_after_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('ecocash', 'EcoCash'), ('bank_transfer', 'Bank Transfer'), ('innbucks', 'InnBucks'), ('onemoney', 'OneMoney')], max_length=20)),
                ('destination_account', models.CharField(help_text='Wallet address or broker account ID', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reference_code', models.CharField(default=transactions.models.generate_reference, max_length=20, unique=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
