# Generated by Django 6.0.3 on 2026-03-27 00:00

import decimal
from django.db import migrations, models


def snapshot_existing_fee_percents(apps, schema_editor):
    Transaction = apps.get_model('transactions', 'Transaction')
    Transaction.objects.filter(fee_percent_applied__isnull=True).update(
        fee_percent_applied=decimal.Decimal('3.00')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fee_percent_applied',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.RunPython(snapshot_existing_fee_percents, migrations.RunPython.noop),
    ]
