# Generated by Django 4.2.23 on 2026-04-02 19:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_fee_percent_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='destination_account_type',
            field=models.CharField(blank=True, choices=[('manual', 'Manual / Other'), ('wallet_address', 'Wallet Address'), ('platform_uid', 'Platform UID'), ('broker_account', 'Broker Account'), ('bank_account', 'Bank Account')], default='manual', help_text='Clarifies whether the account reference is a wallet address, platform UID, broker account, or another identifier.', max_length=30),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider_error_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider_error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider_last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider_status',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.CreateModel(
            name='ProviderWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('binance', 'Binance'), ('ecocash', 'EcoCash')], max_length=20)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('external_event_id', models.CharField(blank=True, max_length=120)),
                ('reference_code', models.CharField(blank=True, max_length=40)),
                ('signature', models.CharField(blank=True, max_length=255)),
                ('signature_status', models.CharField(choices=[('missing', 'Missing'), ('not_configured', 'Not Configured'), ('verified', 'Verified'), ('invalid', 'Invalid')], default='missing', max_length=20)),
                ('processing_status', models.CharField(choices=[('received', 'Received'), ('linked', 'Linked'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='received', max_length=20)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('raw_body', models.TextField(blank=True)),
                ('processing_notes', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Provider Webhook Event',
                'verbose_name_plural': 'Provider Webhook Events',
                'ordering': ['-received_at'],
            },
        ),
    ]
